### ISSUE TITLE
Всё пропало сэр!

### ISSUE THREAD

**Issue by groverz** [afuno/Kinopoisk-API-Gem#15]
Что и следовало ожидать.  Пора переводить на 5.0.0.

Пока не могу понять механизм подписи. Передедаётся в header, там замешан и таймштамп и сам запрос. Копаюсь в smali.

Кто хочет помочь милости прошу (skype, telegram) hav00k.

**Comment by afuno** [comment]
@groverz у меня, к сожалению, сейчас вообще руки не доходят до этого дела. Уже сколько раз собираюсь, да все никак...

**Comment by groverz** [comment]
Да яндекс постарался сингатуру запехать. 

Генерация завеодомого  ключа происходит в функции nativeGetGeoPointJNI В библиотеке libgeo-dictionary-lib.so буду копать дальше, но тоже времени мало. Да и опыта как такового нет. Ладно smali, но тут уже JNI. 

 https://www.onlinedisassembler.com/odaweb/66GugPeY/0

**Comment by groverz** [comment]
https://github.com/groverz/kp_api
